name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of Bun to run"
        required: true
        default: "canary"
        type: string
      path:
        description: "The path to the test files"
        required: true
        default: "test/"
        type: string
      timeout:
        description: "The timeout per file in milliseconds"
        required: true
        default: "15000"
        type: number
jobs:
  test:
    name: ${{ matrix.tag }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: linux-x64
            os: ubuntu-latest
          - tag: linux-x64-baseline
            os: ubuntu-latest
          - tag: darwin-x64
            os: macos-latest
          - tag: darwin-x64-baseline
            os: macos-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - id: setup
        name: Setup
        run: |
          npm install @oven/bun-${{ matrix.tag }}@${{ github.event.inputs.version }}
          chmod +x node_modules/@oven/bun-${{ matrix.tag }}/bin/bun
          cp node_modules/@oven/bun-${{ matrix.tag }}/bin/bun /usr/bin/bun
      - id: test
        name: Test
        run: |
          bun install
          bun install --cwd test
          bun x ts-node --esm scripts/bun-test.ts ${{ github.event.inputs.path }} --isolated --timeout=${{ github.event.inputs.timeout }}
