name: bun
on:
  push:
    branches: [main, bun-actions]
    paths:
      - "src"
      - "test"
  pull_request:
    branches: [main]
    paths:
      - "src"
      - "test"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TEST_TAG: bun-test'

jobs:
  linux-x64:
    name: Linux x64 (${{ matrix.cpu }})
    runs-on: linux-amd64
    timeout-minutes: 90
    strategy:
      matrix:
        cpu: [native, sandybridge]

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git -c submodule."src/bun.js/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j $(nproc)
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Run
        run: |
          rm -rf ${{runner.temp}}/release
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: ghcr.io/oven-sh/bun:canary,ghcr.io/oven-sh/bun:${{github.sha}}
          cache-from: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-${{matrix.cpu}}-amd64
          cache-to: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-${{matrix.cpu}}-amd64,mode=max
          build-args: |
            ARCH=x86_64
            BUILDARCH=amd64
            CPU_TARGET=${{matrix.cpu}}
          platforms: linux/amd64
          target: artifact
          outputs: type=local,dest=${{runner.temp}}/release
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'native' }}
        with:
          name: bun-linux-x64
          path: ${{runner.temp}}/release/bun
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'sandybridge' }}
        with:
          name: bun-linux-x64-generic
          path: ${{runner.temp}}/release/bun
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'native' }}
        with:
          name: bun-dependencies-linux-x64
          path: ${{runner.temp}}/release/bun-dependencies
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'sandybridge' }}
        with:
          name: bun-dependencies-linux-x64-generic
          path: ${{runner.temp}}/release/bun-dependencies
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'native' }}
        with:
          name: bun-linux-x64-profile
          path: ${{runner.temp}}/release/bun-profile
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'sandybridge' }}
        with:
          name: bun-linux-x64-generic-profile
          path: ${{runner.temp}}/release/bun-profile
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'native' }}
        with:
          name: bun-obj-linux-x64
          path: ${{runner.temp}}/release/bun-obj
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.cpu == 'sandybridge' }}
        with:
          name: bun-obj-linux-x64-generic
          path: ${{runner.temp}}/release/bun-obj
  linux-aarch64:
    name: Linux aarch64
    runs-on: linux-arm64
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git -c submodule."src/bun.js/WebKit".update=none submodule update --init --recursive --depth=1 --progress -j $(nproc)
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Run
        run: |
          rm -rf ${{runner.temp}}/release
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/oven-sh/bun:canary,ghcr.io/oven-sh/bun:${{github.sha}}
          push: false
          cache-from: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-aarch64
          cache-to: type=registry,ref=ghcr.io/oven-sh/bun:buildcache-aarch64,mode=max
          build-args: |
            ARCH=aarch64
            BUILDARCH=arm64
            CPU_TARGET=native
          platforms: linux/arm64
          target: artifact
          outputs: type=local,dest=${{runner.temp}}/release
      - uses: actions/upload-artifact@v3
        with:
          name: bun-linux-aarch64
          path: ${{runner.temp}}/release/bun
      - uses: actions/upload-artifact@v3
        with:
          name: bun-dependencies-linux-aarch64
          path: ${{runner.temp}}/release/bun-dependencies
      - uses: actions/upload-artifact@v3
        with:
          name: bun-linux-aarch64-profile
          path: ${{runner.temp}}/release/bun-profile
      - uses: actions/upload-artifact@v3
        with:
          name: bun-obj-linux-aarch64
          path: ${{runner.temp}}/release/bun-obj

  release:
    name: release
    runs-on: ubuntu-18.04
    timeout-minutes: 90
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged) || github.event_name == 'workflow_dispatch'
    needs:
      - linux-x64
      - linux-aarch64
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ${{runner.temp}}/release
      - name: Rename files
        run: |
          cd ${{runner.temp}}/release
          mv bun-linux-x64-generic bun-linux-x64-baseline
          mv bun-linux-x64-generic-profile bun-linux-x64-baseline-profile

          chmod +x bun-linux-x64/*
          chmod +x bun-linux-x64-baseline/*
          chmod +x bun-linux-x64-profile/*
          chmod +x bun-linux-x64-baseline-profile/*
          chmod +x bun-linux-aarch64/*
          chmod +x bun-linux-aarch64-profile/*

          zip -r bun-linux-x64.zip bun-linux-x64
          zip -r bun-linux-x64-baseline.zip bun-linux-x64-baseline
          zip -r bun-linux-x64-profile.zip bun-linux-x64-profile
          zip -r bun-linux-x64-baseline-profile.zip bun-linux-x64-baseline-profile
          zip -r bun-linux-aarch64.zip bun-linux-aarch64
          zip -r bun-linux-aarch64-profile.zip bun-linux-aarch64-profile

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          tag_name: "canary"
          name: Canary
          files: |
            ${{runner.temp}}/release/*.zip
