name: CI workflow for bun
on:
  push:
    branches: [main, bun-actions]
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu:20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jarred-sumner/bun:${{steps.vars.outputs.tag}}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ulimit: "memlock=-1:-1 core=-1:-1"
