name: Run Tests Manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "canary"
        type: string
jobs:
  linux-test:
    name: Tests ${{matrix.tag}} ${{github.event.inputs.version}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: linux-x64
          - tag: linux-x64-baseline
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - id: install-npm
        name: Install (npm)
        run: |
          npm install @oven/bun-${{matrix.tag}}@${{github.event.inputs.version}}
          chmod +x node_modules/@oven/bun-${{matrix.tag}}/bin/bun
          sudo cp node_modules/@oven/bun-${{matrix.tag}}/bin/bun /usr/bin/bun
      - id: test
        name: Test
        run: |
          bun install
          bun install --cwd test
          bunx ts-node --esm scripts/bun-test.ts --isolated test/
